### ISSUE TITLE
sofle

### ISSUE THREAD

**Issue by Domingo821** [edd/zmk-config#5]
Hello, hope all is well. this is not an actual issue, I just can't figure out how to turn on the underglow from your sofle zmk build. I had it working before but things got wonky on my board (its repaired now) I would really appreciate it if you shared what key sequence to input to get to the rbg level

**Comment by edd** [comment]
@Domingo821 I don't have LEDs on this build so I probably didn't add any bindings for that. https://zmk.dev/docs/behaviors/underglow looks like the keys you need, and my [vanana keymap](https://github.com/edd/zmk-config-vanana/blob/master/config/boards/shields/vanana/vanana.keymap#L109) has some in case you need to take a look at how to edit them in

**Comment by Domingo821** [comment]
Thanks for the response. I figured it out,  it was a hardware issue and firmware wasn't sticking.  I ended up using GabrielKim13's fw. I appreciate your insight..happy holidays
